#!/usr/bin/env python3
"""Synthesize a small royalty-free demo song and build examples/demo/Luma_Demo.html without any neural model.
The "vocal" is a sung-like tone (harmonics + vibrato) following an original 16-bar melody; the backing is a soft pad.
Word timings are syllables, so the lyric lane and the scoring can be exercised in tests and screenshots."""
from __future__ import annotations
import json, hashlib, subprocess, sys
from pathlib import Path
import numpy as np, soundfile as sf
ROOT = Path(__file__).resolve().parent.parent; sys.path.insert(0, str(ROOT / 'studio'))
from build_html import build
OUT = ROOT / 'examples' / 'demo'; PKG = OUT / 'Demo'; PKG.mkdir(parents=True, exist_ok=True)
SR = 22050; BPM = 96; beat = 60 / BPM
# (midi, beats) — an original melody in A minor; None = rest
MELODY = [(69, 1), (71, 1), (72, 2), (71, 1), (69, 1), (67, 2), (65, 1), (67, 1), (69, 2), (None, 2),
          (72, 1), (74, 1), (76, 2), (74, 1), (72, 1), (71, 2), (69, 1), (71, 1), (72, 2), (None, 2),
          (76, 1), (74, 1), (72, 1), (71, 1), (69, 2), (67, 2), (65, 1), (67, 1), (69, 1), (71, 1), (72, 4), (None, 4)]
SYLL = ['la', 'la', 'lu', 'na', 'la', 'ne', 'do', 'ri', 'a', 'mo', 'lu', 'ne', 'sa', 'li', 'ta', 'ra', 'no', 'lu', 've', 'na', 'lo', 'si', 'ta', 'ra', 'ma', 'do', 'ri', 'la', 'vo', 'ne']
CHORDS = [[57, 60, 64], [53, 57, 60], [55, 59, 62], [52, 55, 59]]  # Am F G Em
lead = 2.0; t_cursor = lead; notes = []; words = []
for i, (m, b) in enumerate(MELODY):
    if m is not None:
        notes.append({'id': len(notes), 'a': round(t_cursor + .02, 3), 'b': round(t_cursor + b * beat - .04, 3), 'm': float(m), 'n': m, 'q': .95, 'ok': True, 'ignored': False})
        words.append({'a': round(t_cursor + .02, 2), 'b': round(t_cursor + b * beat - .04, 2), 'w': SYLL[len(words) % len(SYLL)], 'c': .99})
    t_cursor += b * beat
duration = t_cursor + 1.5; n = int(duration * SR); t = np.arange(n) / SR
f2m = lambda m: 440 * 2 ** ((m - 69) / 12)
voc = np.zeros(n)
for nt in notes:
    i0, i1 = int(nt['a'] * SR), int(nt['b'] * SR); seg = t[i0:i1] - nt['a']; L = nt['b'] - nt['a']
    f = f2m(nt['m']) * (1 + .006 * np.sin(2 * np.pi * 5.5 * seg) * np.minimum(1, seg / .25)); ph = 2 * np.pi * np.cumsum(f) / SR
    env = np.minimum(1, seg / .03) * np.minimum(1, (L - seg) / .06)
    voc[i0:i1] += env * (np.sin(ph) + .5 * np.sin(2 * ph) + .25 * np.sin(3 * ph) + .12 * np.sin(4 * ph)) * .28
back = np.zeros(n)
for bar in range(int(np.ceil((duration - lead) / (4 * beat)))):
    ch = CHORDS[bar % 4]; a0 = lead + bar * 4 * beat; i0, i1 = int(a0 * SR), min(n, int((a0 + 4 * beat) * SR)); seg = t[i0:i1] - a0
    env = np.minimum(1, seg / .4) * np.minimum(1, (4 * beat - seg) / .4)
    for m in ch: back[i0:i1] += env * np.sin(2 * np.pi * f2m(m - 12) * seg) * .06
    for k in range(4):  # soft click on beats
        j = int((a0 + k * beat) * SR)
        if j + 400 <= n: back[j:j + 400] += np.exp(-np.arange(400) / 80) * .12 * (1.0 if k == 0 else .6)
sf.write(PKG / 'vocal22.wav', np.stack([voc, voc], 1).astype('float32'), SR); sf.write(PKG / 'back22.wav', np.stack([back, back], 1).astype('float32'), SR)
def ffmpeg(*a): subprocess.run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', *map(str, a)], check=True)
for role, src in [('foreground', 'vocal22.wav'), ('backing', 'back22.wav')]:
    for speed, suffix in [(1, ''), (.8, '_80')]:
        ffmpeg('-i', PKG / src, '-af', f'atempo={speed},apad,atrim=duration={duration/speed:.9f}', '-c:a', 'libmp3lame', '-b:a', '96k', '-write_xing', '1', PKG / f'{role}{suffix}.mp3')
hop = .02; ts = np.arange(0, duration, hop); points = []
for tt in ts:
    nt = next((x for x in notes if x['a'] <= tt < x['b']), None); points.append([round(float(tt), 3), nt['m'] if nt else None, .95 if nt else 0, 1 if nt else 0])
phrases = []
for k in range(0, len(notes), 8):
    grp = notes[k:k + 8]; phrases.append({'id': len(phrases) + 1, 'a': round(max(0, grp[0]['a'] - .45), 2), 'b': round(min(duration, grp[-1]['b'] + .45), 2), 'label': f'Фрагмент {len(phrases)+1:02d}', 'verified': False})
mix = np.abs(voc + back); peaks = [round(float(np.max(z)), 3) for z in np.array_split(mix, 1000)]
lines = [{'a': words[k]['a'], 'b': words[min(k + 5, len(words) - 1)]['b'], 'words': words[k:k + 6]} for k in range(0, len(words), 6)]
song = {'schema': 'luma.song.v1', 'title': 'Demo', 'artist': 'Luma', 'duration': duration, 'a4': 440, 'hop': hop, 'status': 'unverified_draft', 'neuralSeparation': False,
        'method': 'Synthetic demo: melody and words generated by examples/make_demo.py', 'warning': 'Демонстраційна пісня: мелодія синтезована, тому ціль тут точна за побудовою.',
        'points': points, 'notes': notes, 'phrases': phrases, 'waveform': peaks, 'initialTime': max(0, notes[0]['a'] - .75),
        'metrics': {'notes': len(notes), 'candidateSeconds': round(sum(x['b'] - x['a'] for x in notes), 2), 'comparableSeconds': round(sum(x['b'] - x['a'] for x in notes), 2), 'comparablePercentOfTrack': round(100 * sum(x['b'] - x['a'] for x in notes) / duration, 1)},
        'createdBy': 'examples/make_demo.py', 'lyrics': lines, 'lyricsSource': 'synthetic syllables', 'sourceId': hashlib.sha256(voc.tobytes()).hexdigest()}
song['id'] = hashlib.sha256(('Demo' + 'Luma' + str(duration) + song['method']).encode()).hexdigest()[:20]
(PKG / 'target.json').write_text(json.dumps(song, ensure_ascii=False, separators=(',', ':')), encoding='utf-8')
for f in ['vocal22.wav', 'back22.wav']: (PKG / f).unlink()
out = build(PKG, OUT / 'Luma_Demo.html'); print('demo:', out, out.stat().st_size, 'bytes;', len(notes), 'notes,', round(duration, 1), 's')
